### ISSUE TITLE
Upgrade Right Hero Section

### ISSUE THREAD

**Issue by Ankit-Saha08** [surajsharma14/Pepsi#5]
## Issue
* The content provided for Ingredients isn't sufficient.
* There is content provided for Description and Nutrition.

## Improvements
- [x] Update the content of Ingredient with real-time data.
- [x] Provide real-time content for Description and Nutrition portions.

## Bonus Improvement
- [ ] Will like to add expand/collapse feature for showing the contents of Nutrition, Description, and Ingredients.

**P.S. - Please assign me this task to make the proposed changes. (hacktoberfest)**

**Comment by Ankit-Saha08** [comment]
I request the maintainer @surajsharma14 to kindly allow to me contribute for the afore mentioned issue.

**Comment by surajsharma14** [comment]
@Ankit-Saha08 assign to you.

**Comment by Ankit-Saha08** [comment]
@surajsharma14 please add the label "hacktoberfest"
