### ISSUE TITLE
Bug: Hero Section Misalignment with Navigation Bar

### ISSUE THREAD

**Issue by Janani-Balasooriya** [surajsharma14/Pepsi#7]
![screencapture](https://github.com/surajsharma14/Pepsi/assets/94961626/50e6e5d8-dd86-4843-9f0d-c54d1e717e3f)

**Comment by Janani-Balasooriya** [comment]
Hi @surajsharma14 , Could you please assign me to this issue?

Thank you!

**Comment by surajsharma14** [comment]
assign to you  @Janani-Balasooriya work on it and fix the issue. but before that make sure follow me

**Comment by Janani-Balasooriya** [comment]
Hi @surajsharma14 , I fixed the issue and made a pull request #8 . Could you please review it when you have a moment?
Thank you!

**Comment by surajsharma14** [comment]
Sure
